### PR TITLE
WIP: started working on new version of migration tool with datastax driver…

### PR DESCRIPTION
**Pull request by pollend**
This is a work in progress to support datastax 4.4. Not all the test seems to be passing so I still need to adjust the code some more. Parts of this api I removed in favor using the configuration for datastax with the prefix property. This should allow for more configuration then the few properties under ClusterConfiguration. I probably need a bit of help validating this and making sure this works correctly. 

I'm working on modifying micronaut cassandra driver. it's possible to override some of the default driver configurations when building the cqlsession. 
```
 CqlSessionBuilder builder = CqlSession.builder().withConfigLoader(new DefaultDriverConfigLoader(new Supplier<Config>() {
            @Override
            public Config get() {

                return ConfigFactory.parseMap(Map.ofEntries(new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONTACT_POINTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SESSION_NAME.getPath(), configuration.getName()),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SESSION_KEYSPACE.getPath(), configuration.getKeyspace()),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONFIG_RELOAD_INTERVAL.getPath(), 0),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_CONSISTENCY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_PAGE_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_SERIAL_CONSISTENCY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_DEFAULT_IDEMPOTENCE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.LOAD_BALANCING_POLICY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.LOAD_BALANCING_POLICY_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.LOAD_BALANCING_LOCAL_DATACENTER.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.LOAD_BALANCING_FILTER_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONNECTION_INIT_QUERY_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONNECTION_SET_KEYSPACE_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONNECTION_MAX_REQUESTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONNECTION_MAX_ORPHAN_REQUESTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONNECTION_WARN_INIT_ERROR.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONNECTION_POOL_LOCAL_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONNECTION_POOL_REMOTE_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.RECONNECT_ON_INIT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.RECONNECTION_POLICY_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.RECONNECTION_BASE_DELAY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.RECONNECTION_MAX_DELAY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.RETRY_POLICY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.RETRY_POLICY_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SPECULATIVE_EXECUTION_POLICY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SPECULATIVE_EXECUTION_POLICY_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SPECULATIVE_EXECUTION_MAX.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SPECULATIVE_EXECUTION_DELAY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.AUTH_PROVIDER_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.AUTH_PROVIDER_USER_NAME.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.AUTH_PROVIDER_PASSWORD.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SSL_ENGINE_FACTORY_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SSL_CIPHER_SUITES.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SSL_HOSTNAME_VALIDATION.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SSL_KEYSTORE_PATH.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SSL_KEYSTORE_PASSWORD.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SSL_TRUSTSTORE_PATH.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SSL_TRUSTSTORE_PASSWORD.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.TIMESTAMP_GENERATOR_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.TIMESTAMP_GENERATOR_FORCE_JAVA_CLOCK.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.TIMESTAMP_GENERATOR_DRIFT_WARNING_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_TRACKER_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_SUCCESS_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_SLOW_THRESHOLD.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_SLOW_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_ERROR_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_MAX_QUERY_LENGTH.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_VALUES.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_MAX_VALUE_LENGTH.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_MAX_VALUES.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOGGER_STACK_TRACES.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_THROTTLER_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_THROTTLER_MAX_CONCURRENT_REQUESTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_THROTTLER_MAX_REQUESTS_PER_SECOND.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_THROTTLER_MAX_QUEUE_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_THROTTLER_DRAIN_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_NODE_STATE_LISTENER_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_SCHEMA_CHANGE_LISTENER_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.ADDRESS_TRANSLATOR_CLASS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.PROTOCOL_VERSION.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.PROTOCOL_COMPRESSION.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.PROTOCOL_MAX_FRAME_LENGTH.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_WARN_IF_SET_KEYSPACE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_TRACE_ATTEMPTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_TRACE_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_TRACE_CONSISTENCY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_SESSION_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_NODE_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_SESSION_CQL_REQUESTS_HIGHEST.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_SESSION_CQL_REQUESTS_DIGITS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_SESSION_CQL_REQUESTS_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_SESSION_THROTTLING_HIGHEST.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_SESSION_THROTTLING_DIGITS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_SESSION_THROTTLING_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_NODE_CQL_MESSAGES_HIGHEST.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_NODE_CQL_MESSAGES_DIGITS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METRICS_NODE_CQL_MESSAGES_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SOCKET_TCP_NODELAY.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SOCKET_KEEP_ALIVE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SOCKET_REUSE_ADDRESS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SOCKET_LINGER_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SOCKET_RECEIVE_BUFFER_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.SOCKET_SEND_BUFFER_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.HEARTBEAT_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.HEARTBEAT_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_TOPOLOGY_WINDOW.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_TOPOLOGY_MAX_EVENTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_SCHEMA_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_SCHEMA_REQUEST_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_SCHEMA_REQUEST_PAGE_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_SCHEMA_REFRESHED_KEYSPACES.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_SCHEMA_WINDOW.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_SCHEMA_MAX_EVENTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.METADATA_TOKEN_MAP_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONTROL_CONNECTION_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONTROL_CONNECTION_AGREEMENT_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONTROL_CONNECTION_AGREEMENT_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CONTROL_CONNECTION_AGREEMENT_WARN.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.PREPARE_ON_ALL_NODES.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REPREPARE_ENABLED.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REPREPARE_CHECK_SYSTEM_TABLE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REPREPARE_MAX_STATEMENTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REPREPARE_MAX_PARALLELISM.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REPREPARE_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_IO_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_IO_SHUTDOWN_QUIET_PERIOD.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_IO_SHUTDOWN_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_IO_SHUTDOWN_UNIT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_ADMIN_SIZE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_ADMIN_SHUTDOWN_QUIET_PERIOD.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_ADMIN_SHUTDOWN_TIMEOUT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_ADMIN_SHUTDOWN_UNIT.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.COALESCER_MAX_RUNS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.COALESCER_INTERVAL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.RESOLVE_CONTACT_POINTS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_TIMER_TICK_DURATION.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_TIMER_TICKS_PER_WHEEL.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.REQUEST_LOG_WARNINGS.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.NETTY_DAEMON.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.CLOUD_SECURE_CONNECT_BUNDLE.getPath(), ""),
                        new AbstractMap.SimpleEntry<String,Object>(DefaultDriverOption.LOAD_BALANCING_POLICY_SLOW_AVOIDANCE.getPath(), "")));
            }
        }));
```

### CODE REVIEW

**Comment by hhandoko** [comment]
Hi, thanks for the PR. For the v4 drivers and also converting to Gradle. Just one comment, I think it's better to retarget this to a separate branch. I can also help to make sure that SNAPSHOT version of are also published to Maven Central.

**Comment by hhandoko** [comment]
I've created a branch with the same name on this repo. Feel free to retarget or I can do it and merge right away.

**Comment by pollend** [comment]
I still need to resolve all the problems with the unit test. versions are not named correctly so that is still an issue. hopefully you can help me resolve some of these problems.

**Comment by hhandoko** [comment]
OK. Will merge this to the feature branch and continue on from there.

**Pull request merged**
